refactor(lint): .env refactor and whitespace lint changes
fix #62

diff --git a/img/set_background b/img/set_background
--- a/img/set_background
+++ b/img/set_background
@@ -5,25 +5,25 @@
 ##
 
 function info () {
-	printf "\r  [ \033[00;34m..\033[0m ] %s\n" "$1"
+    printf "\r  [ \033[00;34m..\033[0m ] %s\n" "$1"
 }
 
 function user () {
-	printf "\r  [ \033[0;33m??\033[0m ] %s " "$1"
+    printf "\r  [ \033[0;33m??\033[0m ] %s " "$1"
 }
 
 function success () {
-	printf "\r\033[2K  [ \033[00;32mOK\033[0m ] %s\n" "$1"
+    printf "\r\033[2K  [ \033[00;32mOK\033[0m ] %s\n" "$1"
 }
 
 function warn () {
-	printf "\r\033[2K  [\033[0;31mWARN\033[0m] %s\n" "$1"
+    printf "\r\033[2K  [\033[0;31mWARN\033[0m] %s\n" "$1"
 }
 
 function fail () {
-	printf "\r\033[2K  [\033[0;31mFAIL\033[0m] %s\n" "$1"
-	echo ''
-	exit 1
+    printf "\r\033[2K  [\033[0;31mFAIL\033[0m] %s\n" "$1"
+    echo ''
+    exit 1
 }
 
 info "Background Image: Checking background image status"
diff --git a/linux/setup_diff_so_fancy b/linux/setup_diff_so_fancy
--- a/linux/setup_diff_so_fancy
+++ b/linux/setup_diff_so_fancy
@@ -8,37 +8,37 @@
 # Pretty output functions
 ##
 function info () {
-	printf "\r  [ \033[00;34m..\033[0m ] %s\n" "$1"
+    printf "\r  [ \033[00;34m..\033[0m ] %s\n" "$1"
 }
 function user () {
-	printf "\r  [ \033[0;33m??\033[0m ] %s " "$1"
+    printf "\r  [ \033[0;33m??\033[0m ] %s " "$1"
 }
 function success () {
-	printf "\r\033[2K  [ \033[00;32mOK\033[0m ] %s\n" "$1"
+    printf "\r\033[2K  [ \033[00;32mOK\033[0m ] %s\n" "$1"
 }
 function warn () {
-	printf "\r\033[2K  [\033[0;31mWARN\033[0m] %s\n" "$1"
+    printf "\r\033[2K  [\033[0;31mWARN\033[0m] %s\n" "$1"
 }
 function fail () {
-	printf "\r\033[2K  [\033[0;31mFAIL\033[0m] %s\n" "$1"
-	echo ''
-	exit 1
+    printf "\r\033[2K  [\033[0;31mFAIL\033[0m] %s\n" "$1"
+    echo ''
+    exit 1
 }
 
 # Setup nice diffing for git
-    export PATH="$HOME/.fancy:$PATH"
-	if [[ $(which diff-so-fancy) == "" ]]; then
-		info "Fancy Diff: Package was not found, downloading now"
-		if git clone https://github.com/so-fancy/diff-so-fancy.git "$HOME"/.fancy &> /dev/null ; then
-			success "Fancy Diff: Package is now installed"
-		else
-			fail "Fancy Diff: Package failed to install"
-		fi
-	else
-		success "Fancy Diff: Package is already installed, updating now"
-		if git -C "$HOME"/.fancy pull &> /dev/null ; then
-			success "Fancy Diff: Package is now updated"
-		else
-			warn "Fancy Diff: Package failed to update"
-		fi
-	fi
+export PATH="$HOME/.fancy:$PATH"
+if [[ $(which diff-so-fancy) == "" ]]; then
+    info "Fancy Diff: Package was not found, downloading now"
+    if git clone https://github.com/so-fancy/diff-so-fancy.git "$HOME"/.fancy &> /dev/null ; then
+        success "Fancy Diff: Package is now installed"
+    else
+        fail "Fancy Diff: Package failed to install"
+    fi
+else
+    success "Fancy Diff: Package is already installed, updating now"
+    if git -C "$HOME"/.fancy pull &> /dev/null ; then
+        success "Fancy Diff: Package is now updated"
+    else
+        warn "Fancy Diff: Package failed to update"
+    fi
+fi
diff --git a/ssh/setup_ssh_directory b/ssh/setup_ssh_directory
--- a/ssh/setup_ssh_directory
+++ b/ssh/setup_ssh_directory
@@ -10,31 +10,31 @@ ssh_directory="$HOME/.ssh"
 # Pretty output functions
 ##
 function info () {
-	printf "\r  [ \033[00;34m..\033[0m ] %s\n" "$1"
+    printf "\r  [ \033[00;34m..\033[0m ] %s\n" "$1"
 }
 function user () {
-	printf "\r  [ \033[0;33m??\033[0m ] %s " "$1"
+    printf "\r  [ \033[0;33m??\033[0m ] %s " "$1"
 }
 function success () {
-	printf "\r\033[2K  [ \033[00;32mOK\033[0m ] %s\n" "$1"
+    printf "\r\033[2K  [ \033[00;32mOK\033[0m ] %s\n" "$1"
 }
 function warn () {
-	printf "\r\033[2K  [\033[0;31mWARN\033[0m] %s\n" "$1"
+    printf "\r\033[2K  [\033[0;31mWARN\033[0m] %s\n" "$1"
 }
 function fail () {
-	printf "\r\033[2K  [\033[0;31mFAIL\033[0m] %s\n" "$1"
-	echo ''
-	exit 1
+    printf "\r\033[2K  [\033[0;31mFAIL\033[0m] %s\n" "$1"
+    echo ''
+    exit 1
 }
 
 if [[ -d "$ssh_directory" ]]; then
-	success "SSH: SSH directory is already created"
+    success "SSH: SSH directory is already created"
 else
-	info "SSH: Setting up SSH directory"
-	if mkdir -p "$ssh_directory" ; then
-		success "SSH: SSH directory is now created"
-	else
-		fail "SSH: SSH directory failed to be created, please check permissions"
-	fi
-	chmod 700 "$ssh_directory"
+    info "SSH: Setting up SSH directory"
+    if mkdir -p "$ssh_directory" ; then
+        success "SSH: SSH directory is now created"
+    else
+        fail "SSH: SSH directory failed to be created, please check permissions"
+    fi
+    chmod 700 "$ssh_directory"
 fi
